use oxc_ast::ast::{BindingPattern, Expression, Program, VariableDeclaration};
use oxc_semantic::Scoping;
use rustc_hash::FxHashMap;

use crate::{
    CompilerDiagnostic,
    edit::{Edit, expand_removal_to_line},
    facts::StaticValue,
    semantic::VindurImports,
};

use super::{
    css::{clean_css, generate_class_rules},
    function_validation::validate_vindur_function,
    scoped::process_scoped_variables,
    static_value::{TemplateContext, evaluate_template},
    style_flags::rewrite_style_flag_selectors,
    styled::{
        StyledComponent, StyledTagContext, missing_style_flag_selectors,
        styled_tag_component_with_attrs, undeclared_style_classes,
    },
    theme_color::{parse_theme_colors, static_color_fallbacks},
    with_component::{
        process_with_component, record_scoped_declarations, style_flags_runtime_call,
    },
};

pub(super) struct VariableTransform<'a> {
    pub imports: &'a VindurImports<'a>,
    pub scoping: &'a Scoping,
    pub program: &'a Program<'a>,
    pub constants: &'a mut FxHashMap<String, StaticValue>,
    pub file_hash: &'a str,
    pub dev: bool,
    pub id_index: &'a mut u32,
    pub edits: &'a mut Vec<Edit>,
    pub css_rules: &'a mut Vec<String>,
    pub styled_components: &'a mut FxHashMap<String, StyledComponent>,
    pub file_path: &'a str,
    pub source: &'a str,
    pub is_exported: bool,
    pub needs_styled_helper: &'a mut bool,
    pub needs_style_flags_helper: &'a mut bool,
    pub scoped_variables: &'a mut FxHashMap<String, String>,
    pub scoped_declaration_spans: &'a mut FxHashMap<String, oxc_span::Span>,
    pub warnings: &'a mut Vec<CompilerDiagnostic>,
}

pub(super) fn process_variable_declaration(
    declaration: &VariableDeclaration<'_>,
    transform: &mut VariableTransform<'_>,
) -> Result<(), CompilerDiagnostic> {
    for declarator in &declaration.declarations {
        let BindingPattern::BindingIdentifier(identifier) = &declarator.id else {
            continue;
        };
        if let Some(initializer) = &declarator.init
            && let Expression::CallExpression(call) = initializer
            && let Expression::Identifier(callee) = &call.callee
            && transform
                .imports
                .matches_import_or_global(callee, "vindurFn")
            && let Some(error) =
                validate_vindur_function(identifier.name.as_str(), initializer, transform.source)
        {
            let span = if error.message.starts_with("vindurFn must be called") {
                identifier.span
            } else {
                error.span
            };
            return Err(CompilerDiagnostic::error(
                transform.file_path,
                transform.source,
                span,
                error.message,
            ));
        }
        if !transform.is_exported
            && let Some(Expression::CallExpression(call)) = &declarator.init
            && let Expression::Identifier(callee) = &call.callee
            && transform
                .imports
                .matches_import_or_global(callee, "vindurFn")
        {
            return Err(CompilerDiagnostic::error(
                transform.file_path,
                transform.source,
                identifier.span,
                format!(
                    "vindurFn \"{}\" must be exported, locally declared vindurFn functions are not supported. If you are trying to use a vindurFn function, you must import it from another file.",
                    identifier.name
                ),
            ));
        }
        if let Some(Expression::CallExpression(call)) = &declarator.init
            && let Expression::Identifier(callee) = &call.callee
            && callee.name.as_str() == "createDynamicCssColor"
        {
            if !call.arguments.is_empty() {
                return Err(CompilerDiagnostic::error(
                    transform.file_path,
                    transform.source,
                    call.span,
                    "createDynamicCssColor() should not be called with an ID parameter. The ID is automatically generated by the compiler."
                        .to_owned(),
                ));
            }
            let id = format!("{}-{}", transform.file_hash, *transform.id_index);
            *transform.id_index += 1;
            transform.constants.insert(
                identifier.name.to_string(),
                StaticValue::DynamicColor { id: id.clone() },
            );
            transform.edits.push(Edit {
                span: call.span,
                replacement: format!("createDynamicCssColor(\"{id}\", {})", transform.dev),
            });
            continue;
        }
        if let Some(Expression::CallExpression(call)) = &declarator.init
            && let Expression::Identifier(callee) = &call.callee
            && callee.name.as_str() == "createStaticThemeColors"
        {
            let colors = parse_theme_colors(&call.arguments).map_err(|error| {
                CompilerDiagnostic::error(
                    transform.file_path,
                    transform.source,
                    error.span,
                    error.message,
                )
            })?;
            transform.constants.insert(
                identifier.name.to_string(),
                StaticValue::ThemeColors(colors),
            );
            continue;
        }
        if let Some(initializer) = &declarator.init
            && process_with_component(
                initializer,
                declaration.span,
                identifier.name.as_str(),
                transform,
            )?
        {
            continue;
        }
        let Some(Expression::TaggedTemplateExpression(tagged)) = &declarator.init else {
            continue;
        };
        let styled_definition = styled_tag_component_with_attrs(
            &tagged.tag,
            tagged.type_arguments.as_deref(),
            &StyledTagContext {
                components: transform.styled_components,
                dev: transform.dev,
                file_hash: transform.file_hash,
                file_path: transform.file_path,
                imports: transform.imports,
                program: transform.program,
                source: transform.source,
            },
        )?;
        if let Some(styled_definition) = styled_definition {
            let base_component = styled_definition.base_component;
            let own_attrs = styled_definition.attrs;
            let own_style_flags = styled_definition.style_flags;
            if declaration.declarations.len() != 1 {
                return Err(CompilerDiagnostic::error(
                    transform.file_path,
                    transform.source,
                    declaration.span,
                    "Styled components must use their own variable declaration".to_owned(),
                ));
            }
            let variable_name = identifier.name.as_str();
            let generated_name = generated_name(
                transform.file_hash,
                *transform.id_index,
                variable_name,
                transform.dev,
            );
            *transform.id_index += 1;
            let content = evaluate_template(
                &tagged.quasi,
                transform.constants,
                transform.scoping,
                transform.file_path,
                transform.source,
                &TemplateContext {
                    variable_name: Some(variable_name),
                    tag_type: "styled",
                },
            )?;
            let content = clean_css(&content);
            let content = if transform.dev {
                content
            } else {
                static_color_fallbacks(&content)
            };
            record_scoped_declarations(
                &content,
                identifier.span,
                transform.scoped_declaration_spans,
            );
            let content = process_scoped_variables(
                &content,
                transform.file_hash,
                transform.dev,
                transform.id_index,
                transform.scoped_variables,
            );
            let style_flags = if own_style_flags.is_empty() {
                base_component.style_flags.clone()
            } else {
                own_style_flags
            };
            if transform.dev {
                transform.warnings.extend(
                    missing_style_flag_selectors(&content, &style_flags)
                        .into_iter()
                        .map(|selector| {
                            CompilerDiagnostic::warning(
                                "",
                                transform.source,
                                identifier.span,
                                format!(
                                    "Warning: Missing modifier styles for \"{selector}\" in {variable_name}"
                                ),
                            )
                        }),
                );
                let usage_prefix = format!("<{variable_name}");
                let suppress_undeclared = !base_component.class_name.is_empty()
                    || (transform.source.contains(&usage_prefix)
                        && (transform.source.contains("cx=")
                            || transform.source.contains("className={`")));
                if !suppress_undeclared {
                    transform.warnings.extend(
                        undeclared_style_classes(&content, &style_flags)
                            .into_iter()
                            .map(|class_name| {
                                CompilerDiagnostic::warning(
                                    "",
                                    transform.source,
                                    identifier.span,
                                    format!(
                                        "The class '{class_name}' is used in CSS but not declared in the component"
                                    ),
                                )
                            }),
                    );
                }
            }
            let content = rewrite_style_flag_selectors(&content, &style_flags);
            transform
                .css_rules
                .extend(generate_class_rules(&generated_name, &content));
            let complete_class_name = if base_component.class_name.is_empty() {
                generated_name.clone()
            } else {
                format!("{} {generated_name}", base_component.class_name)
            };
            transform.constants.insert(
                variable_name.to_owned(),
                StaticValue::ClassName(generated_name.clone()),
            );
            let attrs = own_attrs.or_else(|| base_component.attrs.clone());
            let runtime = transform.is_exported || attrs.is_some() || base_component.runtime;
            if runtime {
                let attrs_argument = attrs
                    .as_ref()
                    .map_or(String::new(), |value| format!(", {value}"));
                let replacement = if style_flags.is_empty() {
                    *transform.needs_styled_helper = true;
                    format!(
                        "_vSC(\"{}\", \"{complete_class_name}\"{attrs_argument})",
                        base_component.element,
                    )
                } else {
                    *transform.needs_style_flags_helper = true;
                    style_flags_runtime_call(
                        &style_flags,
                        &complete_class_name,
                        &base_component.element,
                        base_component.element_is_identifier,
                        attrs.as_deref(),
                    )
                };
                transform.edits.push(Edit {
                    span: tagged.span,
                    replacement,
                });
                transform.styled_components.insert(
                    variable_name.to_owned(),
                    StyledComponent {
                        attrs,
                        class_name: complete_class_name,
                        element: base_component.element,
                        element_is_identifier: base_component.element_is_identifier,
                        runtime: true,
                        style_flags,
                    },
                );
                continue;
            }
            transform.styled_components.insert(
                variable_name.to_owned(),
                StyledComponent {
                    attrs: None,
                    class_name: complete_class_name,
                    element: base_component.element,
                    element_is_identifier: base_component.element_is_identifier,
                    runtime: false,
                    style_flags,
                },
            );
            transform.edits.push(Edit {
                span: expand_removal_to_line(transform.source, declaration.span),
                replacement: String::new(),
            });
            continue;
        }

        let Some(tag_name) = imported_tag_name(&tagged.tag, transform.imports) else {
            continue;
        };
        if tag_name == "createGlobalStyle" {
            let content = evaluate_template(
                &tagged.quasi,
                transform.constants,
                transform.scoping,
                transform.file_path,
                transform.source,
                &TemplateContext {
                    variable_name: Some(identifier.name.as_str()),
                    tag_type: "createGlobalStyle",
                },
            )?;
            let content = clean_css(&content);
            record_scoped_declarations(
                &content,
                identifier.span,
                transform.scoped_declaration_spans,
            );
            let content = process_scoped_variables(
                &content,
                transform.file_hash,
                transform.dev,
                transform.id_index,
                transform.scoped_variables,
            );
            if !content.is_empty() {
                transform.css_rules.push(content);
            }
            transform.edits.push(Edit {
                span: expand_removal_to_line(transform.source, declaration.span),
                replacement: String::new(),
            });
            continue;
        }
        if !matches!(tag_name, "css" | "keyframes") {
            continue;
        }

        let variable_name = identifier.name.as_str();
        let generated_name = generated_name(
            transform.file_hash,
            *transform.id_index,
            variable_name,
            transform.dev,
        );
        *transform.id_index += 1;

        let content = evaluate_template(
            &tagged.quasi,
            transform.constants,
            transform.scoping,
            transform.file_path,
            transform.source,
            &TemplateContext {
                variable_name: Some(variable_name),
                tag_type: "css",
            },
        )?;
        let content = clean_css(&content);
        let content = if transform.dev {
            content
        } else {
            static_color_fallbacks(&content)
        };
        record_scoped_declarations(
            &content,
            identifier.span,
            transform.scoped_declaration_spans,
        );
        let content = process_scoped_variables(
            &content,
            transform.file_hash,
            transform.dev,
            transform.id_index,
            transform.scoped_variables,
        );
        if !content.is_empty() {
            let rules = if tag_name == "keyframes" {
                vec![format!("@keyframes {generated_name} {{\n  {content}\n}}")]
            } else {
                generate_class_rules(&generated_name, &content)
            };
            transform.css_rules.extend(rules);
        }
        transform.constants.insert(
            variable_name.to_owned(),
            if tag_name == "css" {
                StaticValue::CssClass {
                    name: generated_name.clone(),
                    css: content,
                }
            } else {
                StaticValue::Keyframes(generated_name.clone())
            },
        );
        transform.edits.push(Edit {
            span: tagged.span,
            replacement: format!("\"{generated_name}\""),
        });
    }
    Ok(())
}

fn generated_name(file_hash: &str, id_index: u32, variable_name: &str, dev: bool) -> String {
    if dev {
        format!("{file_hash}-{id_index}-{variable_name}")
    } else {
        format!("{file_hash}-{id_index}")
    }
}

pub(super) fn imported_tag_name<'a>(
    tag: &Expression<'_>,
    imports: &'a VindurImports<'_>,
) -> Option<&'a str> {
    imports.get_expression(tag)
}
